tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "git"
brew "mas"

brew "stow"
brew "zoxide"
brew "fd"
brew "bat"
brew "exa"
brew "awscli"
brew "kubectl"
brew "kubectx"

cask "authy"
cask "aws-vault"
cask "docker"
cask "intellij-idea"
cask "iterm2"
cask "slack"
cask "visual-studio-code"
cask "zoom"

mas "Bitwarden", id: 1352778147
