tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "git"
brew "mas"

brew "stow"
brew "fzf"
brew "zoxide"
brew "fd"
brew "bat"
brew "exa"

cask "intellij-idea"
cask "iterm2"
cask "slack"
cask "visual-studio-code"

mas "Bitwarden", id: 1352778147
